name: Validate JSON

on:
  push:
    paths:
      - '**/*.json'  # Adjust this to match the path of your JSON file(s)

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'  # Use the version you need

    - name: Install dependencies
      run: pip install pyyaml  # In case you need to work with YAML as well

    - name: Run validation script
      run: python validate_json.py test_file.json
