name: Validate JSON

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.json'  # Adjust this to match the path of your JSON file(s)

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'  # Use the version you need


    - name: Run validation script
      run: python validate_json.py test_file.json
